# Generated by Django 4.2.5 on 2023-09-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('access_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('refresh_key', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='refresh_key')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('access_key_expired', models.DateTimeField(verbose_name='Expired')),
                ('refresh_key_expired', models.DateTimeField(blank=True, null=True, verbose_name='Refresh Key Expired')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
