# Generated by Django 4.2.5 on 2023-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='article_body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
